--
-- PostgreSQL database dump
--

\restrict 0zjr6QXBrRiwQRNJIOqm9aI53eU1k66K4Pcj3HeJVsoZVXIjndfalEpXVBdUSpj

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: backup_srh_db_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO backup_srh_db_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academics_course; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.academics_course (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    level smallint NOT NULL,
    semester character varying(10) NOT NULL,
    department_id bigint NOT NULL,
    CONSTRAINT academics_course_level_check CHECK ((level >= 0))
);


ALTER TABLE public.academics_course OWNER TO backup_srh_db_user;

--
-- Name: academics_course_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.academics_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academics_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: academics_department; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.academics_department (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    slug character varying(160) NOT NULL,
    faculty_id bigint NOT NULL
);


ALTER TABLE public.academics_department OWNER TO backup_srh_db_user;

--
-- Name: academics_department_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.academics_department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academics_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: academics_faculty; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.academics_faculty (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    slug character varying(160) NOT NULL
);


ALTER TABLE public.academics_faculty OWNER TO backup_srh_db_user;

--
-- Name: academics_faculty_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.academics_faculty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academics_faculty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    full_name character varying(225) NOT NULL,
    faculty character varying(225) NOT NULL,
    department character varying(225) NOT NULL,
    role character varying(20) NOT NULL,
    level character varying(12) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO backup_srh_db_user;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO backup_srh_db_user;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO backup_srh_db_user;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO backup_srh_db_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO backup_srh_db_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO backup_srh_db_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO backup_srh_db_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO backup_srh_db_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO backup_srh_db_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO backup_srh_db_user;

--
-- Name: interactions_comment; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.interactions_comment (
    id bigint NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    parent_id bigint,
    resource_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.interactions_comment OWNER TO backup_srh_db_user;

--
-- Name: interactions_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.interactions_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interactions_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interactions_notification; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.interactions_notification (
    id bigint NOT NULL,
    message character varying(200) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL
);


ALTER TABLE public.interactions_notification OWNER TO backup_srh_db_user;

--
-- Name: interactions_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.interactions_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interactions_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interactions_rating; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.interactions_rating (
    id bigint NOT NULL,
    score smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    resource_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT interactions_rating_score_check CHECK ((score >= 0))
);


ALTER TABLE public.interactions_rating OWNER TO backup_srh_db_user;

--
-- Name: interactions_rating_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.interactions_rating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interactions_rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources_category; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.resources_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.resources_category OWNER TO backup_srh_db_user;

--
-- Name: resources_category_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.resources_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources_resources; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.resources_resources (
    id bigint NOT NULL,
    title character varying(75) NOT NULL,
    description text NOT NULL,
    file character varying(100),
    created_at timestamp with time zone CONSTRAINT resources_resources_craeted_at_not_null NOT NULL,
    category_id bigint NOT NULL,
    uploaded_by_id bigint NOT NULL,
    download_count integer NOT NULL,
    resource_type character varying(10) NOT NULL,
    link character varying(200)
);


ALTER TABLE public.resources_resources OWNER TO backup_srh_db_user;

--
-- Name: resources_resources_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.resources_resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources_resources_tags; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.resources_resources_tags (
    id bigint NOT NULL,
    resources_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.resources_resources_tags OWNER TO backup_srh_db_user;

--
-- Name: resources_resources_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.resources_resources_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_resources_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources_resourcesubmission; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.resources_resourcesubmission (
    id bigint NOT NULL,
    resource_type character varying(10) NOT NULL,
    title character varying(75) NOT NULL,
    description text NOT NULL,
    file character varying(100),
    link character varying(200),
    status character varying(10) NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    approved_at timestamp with time zone,
    approved_by_id bigint,
    category_id bigint NOT NULL,
    submitted_by_id bigint NOT NULL
);


ALTER TABLE public.resources_resourcesubmission OWNER TO backup_srh_db_user;

--
-- Name: resources_resourcesubmission_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.resources_resourcesubmission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_resourcesubmission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources_tag; Type: TABLE; Schema: public; Owner: backup_srh_db_user
--

CREATE TABLE public.resources_tag (
    id bigint NOT NULL,
    name character varying(65) NOT NULL
);


ALTER TABLE public.resources_tag OWNER TO backup_srh_db_user;

--
-- Name: resources_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE public.resources_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: academics_course; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.academics_course (id, code, title, level, semester, department_id) FROM stdin;
\.


--
-- Data for Name: academics_department; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.academics_department (id, name, slug, faculty_id) FROM stdin;
\.


--
-- Data for Name: academics_faculty; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.academics_faculty (id, name, slug) FROM stdin;
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.accounts_user (id, password, last_login, is_superuser, email, full_name, faculty, department, role, level, is_active, is_staff, date_joined) FROM stdin;
3	pbkdf2_sha256$1000000$epOXZxYKch31KQygqnmdIG$UwrZkFe7Q9VkPGWKJR1WwRm4QagmmWlHOdO2mhCpCGA=	\N	f	abdulhamidyunusa409@gmail.com	Abdulhamid Yunusa	Faculty of Computing	Information Technology	student		t	f	2026-09-14 10:24:26.124335+00
4	pbkdf2_sha256$1000000$TM1F4JrRU638mvCTSWX5vM$qrofuWLDYxuZLGwuck0tK0nuV/7vIcE7TG9k+ppFj7c=	\N	f	abubakaryahayakudan@gmail.com	Abubakar Yahaya	Faculty of Science	Physics	student		t	f	2026-09-14 17:32:52.610117+00
5	pbkdf2_sha256$1000000$67MylGHwXw1SXgL2VdOTVi$hTr9zxPGYoloJirWAzOkSsKvXwHl0F6LBgfC5Cn0zmA=	\N	f	khadijasalisu24434@gmail.com	Khadija salisu	Faculty of Science	Biology	student		t	f	2026-09-14 18:37:29.024298+00
1	pbkdf2_sha256$1000000$iSkceCP4b1XmD1Sd4FHv2o$cK2EevBThJf/7pjXpgm5G9kFJD1MpW0UU5pNO0cs5l8=	2026-09-15 19:34:02.035705+00	t	houzsaad@admin.com	Huzaifa Sa'ad			admin		t	t	2026-09-14 00:35:40.065382+00
2	pbkdf2_sha256$1000000$bWq2rciK7Rfwd0C62DfV1F$wBGYijUy2iCxcW5dapUlMAiMnXANpYFNORnTNDhg0bU=	\N	f	hz@gmail.com	Huzaifa Sa'ad	Faculty of Computing	Information Technology	student	300	t	f	2026-09-14 00:37:09.332276+00
6	pbkdf2_sha256$1000000$WH1Yk0VdJhn5hpkrfmQHfK$v6DTUkLfhOmZx/mp6eeRtT+0LKQoUatld0QQgmmfkNc=	\N	f	slm@gmail.com	Salama Aminu	Faculty of Education	Education Physics	student		t	f	2026-09-15 19:35:58.231324+00
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
1	2	33
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add category	7	add_category
26	Can change category	7	change_category
27	Can delete category	7	delete_category
28	Can view category	7	view_category
29	Can add resources	8	add_resources
30	Can change resources	8	change_resources
31	Can delete resources	8	delete_resources
32	Can view resources	8	view_resources
33	Can approve resource	8	can_approve_resource
34	Can add tag	9	add_tag
35	Can change tag	9	change_tag
36	Can delete tag	9	delete_tag
37	Can view tag	9	view_tag
38	Can add resource submission	10	add_resourcesubmission
39	Can change resource submission	10	change_resourcesubmission
40	Can delete resource submission	10	delete_resourcesubmission
41	Can view resource submission	10	view_resourcesubmission
42	Can add comment	11	add_comment
43	Can change comment	11	change_comment
44	Can delete comment	11	delete_comment
45	Can view comment	11	view_comment
46	Can add notification	12	add_notification
47	Can change notification	12	change_notification
48	Can delete notification	12	delete_notification
49	Can view notification	12	view_notification
50	Can add rating	13	add_rating
51	Can change rating	13	change_rating
52	Can delete rating	13	delete_rating
53	Can view rating	13	view_rating
54	Can add faculty	14	add_faculty
55	Can change faculty	14	change_faculty
56	Can delete faculty	14	delete_faculty
57	Can view faculty	14	view_faculty
58	Can add department	15	add_department
59	Can change department	15	change_department
60	Can delete department	15	delete_department
61	Can view department	15	view_department
62	Can add course	16	add_course
63	Can change course	16	change_course
64	Can delete course	16	delete_course
65	Can view course	16	view_course
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-09-15 19:34:43.133327+00	2	Huzaifa Sa'ad (student)	2	[{"changed": {"fields": ["Level", "User permissions"]}}]	6	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	resources	category
8	resources	resources
9	resources	tag
10	resources	resourcesubmission
11	interactions	comment
12	interactions	notification
13	interactions	rating
14	academics	faculty
15	academics	department
16	academics	course
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	academics	0001_initial	2026-09-14 00:35:37.874486+00
2	contenttypes	0001_initial	2026-09-14 00:35:37.884+00
3	contenttypes	0002_remove_content_type_name	2026-09-14 00:35:37.894599+00
4	auth	0001_initial	2026-09-14 00:35:37.991223+00
5	auth	0002_alter_permission_name_max_length	2026-09-14 00:35:37.998888+00
6	auth	0003_alter_user_email_max_length	2026-09-14 00:35:38.077129+00
7	auth	0004_alter_user_username_opts	2026-09-14 00:35:38.083585+00
8	auth	0005_alter_user_last_login_null	2026-09-14 00:35:38.090358+00
9	auth	0006_require_contenttypes_0002	2026-09-14 00:35:38.093973+00
10	auth	0007_alter_validators_add_error_messages	2026-09-14 00:35:38.099515+00
11	auth	0008_alter_user_username_max_length	2026-09-14 00:35:38.105063+00
12	auth	0009_alter_user_last_name_max_length	2026-09-14 00:35:38.11085+00
13	auth	0010_alter_group_name_max_length	2026-09-14 00:35:38.119198+00
14	auth	0011_update_proxy_permissions	2026-09-14 00:35:38.125363+00
15	auth	0012_alter_user_first_name_max_length	2026-09-14 00:35:38.17694+00
16	accounts	0001_initial	2026-09-14 00:35:38.282198+00
17	admin	0001_initial	2026-09-14 00:35:38.37286+00
18	admin	0002_logentry_remove_auto_add	2026-09-14 00:35:38.38054+00
19	admin	0003_logentry_add_action_flag_choices	2026-09-14 00:35:38.387948+00
20	resources	0001_initial	2026-09-14 00:35:38.414167+00
21	resources	0002_rename_craeted_at_resources_created_at	2026-09-14 00:35:38.481112+00
22	resources	0003_tag_resources_tags	2026-09-14 00:35:38.579107+00
23	resources	0004_remove_resources_tags_resources_download_count	2026-09-14 00:35:38.595857+00
24	resources	0005_resources_tags	2026-09-14 00:35:38.678941+00
25	resources	0007_seed_categories	2026-09-14 00:35:38.706857+00
26	resources	0006_resources_resource_type	2026-09-14 00:35:38.718191+00
27	resources	0008_merge_20260623_0134	2026-09-14 00:35:38.721218+00
28	resources	0009_resources_link_alter_resources_file	2026-09-14 00:35:38.738694+00
29	resources	0010_alter_resources_resource_type	2026-09-14 00:35:38.776558+00
30	resources	0011_alter_resources_file	2026-09-14 00:35:38.786278+00
31	interactions	0001_initial	2026-09-14 00:35:38.89797+00
32	interactions	0002_alter_rating_resource_alter_rating_score	2026-09-14 00:35:38.973746+00
33	resources	0012_alter_resources_options	2026-09-14 00:35:38.983988+00
34	resources	0013_resourcesubmission	2026-09-14 00:35:39.071061+00
35	resources	0014_alter_resources_resource_type_and_more	2026-09-14 00:35:39.086906+00
36	sessions	0001_initial	2026-09-14 00:35:39.098799+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
u5jtmgnbw5ckrjie7ow348avqpvfk4z8	.eJxVjEEOwiAUBe_C2hCghIJL956B_A9PqRpISrtqvLs26UK3b2beJiKtS4lrxxynLM5Ci9PvxpSeqDvID6r3JlOryzyx3BV50C6vLeN1Ody_g0K9fGsHA2U8gk5aATrcArF2IQzE8D4Z6wxpZu-UHS0lZvAQshkdMmC8eH8A6VY4ZQ:1x6Yuo:-qhfx9o_qWNeQGWVGh9hrlKFEL0rYXjVOZRlAkV1wAc	2026-09-29 19:34:02.038574+00
\.


--
-- Data for Name: interactions_comment; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.interactions_comment (id, body, created_at, parent_id, resource_id, user_id) FROM stdin;
1	yokk	2026-09-15 22:26:14.266493+00	\N	2	6
2	yooo	2026-09-15 22:26:41.380053+00	\N	1	6
3	nice one	2026-09-15 22:31:28.589361+00	\N	5	2
4	i am the best wooo	2026-09-15 22:32:06.541075+00	\N	6	2
\.


--
-- Data for Name: interactions_notification; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.interactions_notification (id, message, is_read, created_at, owner_id) FROM stdin;
1	Salama Aminu rated on your resource "x link" 4 starts	f	2026-09-15 22:26:11.196311+00	2
2	Salama Aminu commented on your resource "x link"	f	2026-09-15 22:26:14.270317+00	2
3	Salama Aminu rated on your resource "COS202 test" 4 starts	f	2026-09-15 22:26:28.046761+00	2
4	Salama Aminu commented on your resource "COS202 test"	f	2026-09-15 22:26:41.383907+00	2
5	Huzaifa Sa'ad rated on your resource "y link" 4 starts	f	2026-09-15 22:31:21.70066+00	6
6	Huzaifa Sa'ad commented on your resource "y link"	f	2026-09-15 22:31:28.59294+00	6
7	Huzaifa Sa'ad rated on your resource "image" 5 starts	f	2026-09-15 22:31:44.367376+00	6
8	Huzaifa Sa'ad commented on your resource "image"	f	2026-09-15 22:32:06.546076+00	6
\.


--
-- Data for Name: interactions_rating; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.interactions_rating (id, score, created_at, resource_id, user_id) FROM stdin;
1	4	2026-09-15 22:26:11.191632+00	2	6
2	4	2026-09-15 22:26:28.042539+00	1	6
3	4	2026-09-15 22:31:21.696501+00	5	2
4	5	2026-09-15 22:31:44.363855+00	6	2
\.


--
-- Data for Name: resources_category; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.resources_category (id, name, description) FROM stdin;
1	Image	
2	Video	
3	Url	
\.


--
-- Data for Name: resources_resources; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.resources_resources (id, title, description, file, created_at, category_id, uploaded_by_id, download_count, resource_type, link) FROM stdin;
2	x link	official x link		2026-09-15 19:35:24.910509+00	3	2	0	link	https://x.com
3	IFT202	PDF file	media/resources/week11-guide.html_u5zkgd	2026-09-15 19:35:26.164209+00	1	2	0	pdf	\N
1	COS202 test	image	media/resources/1000845390_rr1pyj.jpg	2026-09-15 19:35:24.749661+00	1	2	2	image	\N
4	EDU404	images of edu404	media/resources/1000844444_egemgz.jpg	2026-09-15 22:29:46.804476+00	1	6	0	image	\N
5	y link	official link of y site		2026-09-15 22:30:05.402624+00	3	6	0	link	https://y.com
6	image	imagination	media/resources/1000846085_vgs9si.mp4	2026-09-15 22:30:55.751582+00	1	6	0	image	\N
\.


--
-- Data for Name: resources_resources_tags; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.resources_resources_tags (id, resources_id, tag_id) FROM stdin;
\.


--
-- Data for Name: resources_resourcesubmission; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.resources_resourcesubmission (id, resource_type, title, description, file, link, status, submitted_at, approved_at, approved_by_id, category_id, submitted_by_id) FROM stdin;
2	image	COS202 test	image	media/resources/1000845390_rr1pyj.jpg	\N	approved	2026-09-15 19:31:44.483493+00	2026-09-15 19:35:24.752405+00	2	1	2
1	link	x link	official x link		https://x.com	approved	2026-09-15 19:31:08.930171+00	2026-09-15 19:35:24.912577+00	2	3	2
3	pdf	IFT202	PDF file	media/resources/week11-guide.html_u5zkgd	\N	approved	2026-09-15 19:32:39.41202+00	2026-09-15 19:35:26.165972+00	2	1	2
4	image	EDU404	images of edu404	media/resources/1000844444_egemgz.jpg	\N	approved	2026-09-15 19:37:22.027018+00	2026-09-15 22:29:46.80888+00	2	1	6
5	link	y link	official link of y site		https://y.com	approved	2026-09-15 19:38:09.502933+00	2026-09-15 22:30:05.404961+00	2	3	6
6	image	image	imagination	media/resources/1000846085_vgs9si.mp4	\N	approved	2026-09-15 22:25:57.070942+00	2026-09-15 22:30:55.753668+00	2	1	6
\.


--
-- Data for Name: resources_tag; Type: TABLE DATA; Schema: public; Owner: backup_srh_db_user
--

COPY public.resources_tag (id, name) FROM stdin;
\.


--
-- Name: academics_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.academics_course_id_seq', 1, false);


--
-- Name: academics_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.academics_department_id_seq', 1, false);


--
-- Name: academics_faculty_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.academics_faculty_id_seq', 1, false);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 6, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 65, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 36, true);


--
-- Name: interactions_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.interactions_comment_id_seq', 4, true);


--
-- Name: interactions_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.interactions_notification_id_seq', 8, true);


--
-- Name: interactions_rating_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.interactions_rating_id_seq', 4, true);


--
-- Name: resources_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.resources_category_id_seq', 3, true);


--
-- Name: resources_resources_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.resources_resources_id_seq', 6, true);


--
-- Name: resources_resources_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.resources_resources_tags_id_seq', 1, false);


--
-- Name: resources_resourcesubmission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.resources_resourcesubmission_id_seq', 6, true);


--
-- Name: resources_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_srh_db_user
--

SELECT pg_catalog.setval('public.resources_tag_id_seq', 1, false);


--
-- Name: academics_course academics_course_department_id_code_a82f50fe_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_course
    ADD CONSTRAINT academics_course_department_id_code_a82f50fe_uniq UNIQUE (department_id, code);


--
-- Name: academics_course academics_course_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_course
    ADD CONSTRAINT academics_course_pkey PRIMARY KEY (id);


--
-- Name: academics_department academics_department_faculty_id_name_d401e7d0_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_department
    ADD CONSTRAINT academics_department_faculty_id_name_d401e7d0_uniq UNIQUE (faculty_id, name);


--
-- Name: academics_department academics_department_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_department
    ADD CONSTRAINT academics_department_pkey PRIMARY KEY (id);


--
-- Name: academics_faculty academics_faculty_name_key; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_faculty
    ADD CONSTRAINT academics_faculty_name_key UNIQUE (name);


--
-- Name: academics_faculty academics_faculty_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_faculty
    ADD CONSTRAINT academics_faculty_pkey PRIMARY KEY (id);


--
-- Name: academics_faculty academics_faculty_slug_key; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_faculty
    ADD CONSTRAINT academics_faculty_slug_key UNIQUE (slug);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: interactions_comment interactions_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_comment
    ADD CONSTRAINT interactions_comment_pkey PRIMARY KEY (id);


--
-- Name: interactions_notification interactions_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_notification
    ADD CONSTRAINT interactions_notification_pkey PRIMARY KEY (id);


--
-- Name: interactions_rating interactions_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_rating
    ADD CONSTRAINT interactions_rating_pkey PRIMARY KEY (id);


--
-- Name: interactions_rating interactions_rating_resource_id_user_id_46185599_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_rating
    ADD CONSTRAINT interactions_rating_resource_id_user_id_46185599_uniq UNIQUE (resource_id, user_id);


--
-- Name: resources_category resources_category_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_category
    ADD CONSTRAINT resources_category_pkey PRIMARY KEY (id);


--
-- Name: resources_resources resources_resources_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resources
    ADD CONSTRAINT resources_resources_pkey PRIMARY KEY (id);


--
-- Name: resources_resources_tags resources_resources_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resources_tags
    ADD CONSTRAINT resources_resources_tags_pkey PRIMARY KEY (id);


--
-- Name: resources_resources_tags resources_resources_tags_resources_id_tag_id_96f9cf49_uniq; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resources_tags
    ADD CONSTRAINT resources_resources_tags_resources_id_tag_id_96f9cf49_uniq UNIQUE (resources_id, tag_id);


--
-- Name: resources_resourcesubmission resources_resourcesubmission_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resourcesubmission
    ADD CONSTRAINT resources_resourcesubmission_pkey PRIMARY KEY (id);


--
-- Name: resources_tag resources_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_tag
    ADD CONSTRAINT resources_tag_name_key UNIQUE (name);


--
-- Name: resources_tag resources_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_tag
    ADD CONSTRAINT resources_tag_pkey PRIMARY KEY (id);


--
-- Name: academics_course_department_id_afe8fcd1; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX academics_course_department_id_afe8fcd1 ON public.academics_course USING btree (department_id);


--
-- Name: academics_department_faculty_id_97971229; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX academics_department_faculty_id_97971229 ON public.academics_department USING btree (faculty_id);


--
-- Name: academics_department_slug_ba26b170; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX academics_department_slug_ba26b170 ON public.academics_department USING btree (slug);


--
-- Name: academics_department_slug_ba26b170_like; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX academics_department_slug_ba26b170_like ON public.academics_department USING btree (slug varchar_pattern_ops);


--
-- Name: academics_faculty_name_8f9145e3_like; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX academics_faculty_name_8f9145e3_like ON public.academics_faculty USING btree (name varchar_pattern_ops);


--
-- Name: academics_faculty_slug_98759f79_like; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX academics_faculty_slug_98759f79_like ON public.academics_faculty USING btree (slug varchar_pattern_ops);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: interactions_comment_parent_id_e2664b28; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX interactions_comment_parent_id_e2664b28 ON public.interactions_comment USING btree (parent_id);


--
-- Name: interactions_comment_resource_id_28e52644; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX interactions_comment_resource_id_28e52644 ON public.interactions_comment USING btree (resource_id);


--
-- Name: interactions_comment_user_id_3985ecff; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX interactions_comment_user_id_3985ecff ON public.interactions_comment USING btree (user_id);


--
-- Name: interactions_notification_owner_id_f2303c96; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX interactions_notification_owner_id_f2303c96 ON public.interactions_notification USING btree (owner_id);


--
-- Name: interactions_rating_resource_id_93076e68; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX interactions_rating_resource_id_93076e68 ON public.interactions_rating USING btree (resource_id);


--
-- Name: interactions_rating_user_id_37f604d4; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX interactions_rating_user_id_37f604d4 ON public.interactions_rating USING btree (user_id);


--
-- Name: resources_resources_category_id_fd376920; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX resources_resources_category_id_fd376920 ON public.resources_resources USING btree (category_id);


--
-- Name: resources_resources_tags_resources_id_99f9126d; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX resources_resources_tags_resources_id_99f9126d ON public.resources_resources_tags USING btree (resources_id);


--
-- Name: resources_resources_tags_tag_id_58deb725; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX resources_resources_tags_tag_id_58deb725 ON public.resources_resources_tags USING btree (tag_id);


--
-- Name: resources_resources_uploaded_by_id_9abfb0e3; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX resources_resources_uploaded_by_id_9abfb0e3 ON public.resources_resources USING btree (uploaded_by_id);


--
-- Name: resources_resourcesubmission_approved_by_id_e344bae2; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX resources_resourcesubmission_approved_by_id_e344bae2 ON public.resources_resourcesubmission USING btree (approved_by_id);


--
-- Name: resources_resourcesubmission_category_id_3332309f; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX resources_resourcesubmission_category_id_3332309f ON public.resources_resourcesubmission USING btree (category_id);


--
-- Name: resources_resourcesubmission_submitted_by_id_d102baf5; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX resources_resourcesubmission_submitted_by_id_d102baf5 ON public.resources_resourcesubmission USING btree (submitted_by_id);


--
-- Name: resources_tag_name_0b3bfec4_like; Type: INDEX; Schema: public; Owner: backup_srh_db_user
--

CREATE INDEX resources_tag_name_0b3bfec4_like ON public.resources_tag USING btree (name varchar_pattern_ops);


--
-- Name: academics_course academics_course_department_id_afe8fcd1_fk_academics; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_course
    ADD CONSTRAINT academics_course_department_id_afe8fcd1_fk_academics FOREIGN KEY (department_id) REFERENCES public.academics_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: academics_department academics_department_faculty_id_97971229_fk_academics; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.academics_department
    ADD CONSTRAINT academics_department_faculty_id_97971229_fk_academics FOREIGN KEY (faculty_id) REFERENCES public.academics_faculty(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: interactions_comment interactions_comment_parent_id_e2664b28_fk_interacti; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_comment
    ADD CONSTRAINT interactions_comment_parent_id_e2664b28_fk_interacti FOREIGN KEY (parent_id) REFERENCES public.interactions_comment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: interactions_comment interactions_comment_resource_id_28e52644_fk_resources; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_comment
    ADD CONSTRAINT interactions_comment_resource_id_28e52644_fk_resources FOREIGN KEY (resource_id) REFERENCES public.resources_resources(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: interactions_comment interactions_comment_user_id_3985ecff_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_comment
    ADD CONSTRAINT interactions_comment_user_id_3985ecff_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: interactions_notification interactions_notification_owner_id_f2303c96_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_notification
    ADD CONSTRAINT interactions_notification_owner_id_f2303c96_fk_accounts_user_id FOREIGN KEY (owner_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: interactions_rating interactions_rating_resource_id_93076e68_fk_resources; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_rating
    ADD CONSTRAINT interactions_rating_resource_id_93076e68_fk_resources FOREIGN KEY (resource_id) REFERENCES public.resources_resources(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: interactions_rating interactions_rating_user_id_37f604d4_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.interactions_rating
    ADD CONSTRAINT interactions_rating_user_id_37f604d4_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resources_tags resources_resources__resources_id_99f9126d_fk_resources; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resources_tags
    ADD CONSTRAINT resources_resources__resources_id_99f9126d_fk_resources FOREIGN KEY (resources_id) REFERENCES public.resources_resources(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resources resources_resources_category_id_fd376920_fk_resources; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resources
    ADD CONSTRAINT resources_resources_category_id_fd376920_fk_resources FOREIGN KEY (category_id) REFERENCES public.resources_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resources_tags resources_resources_tags_tag_id_58deb725_fk_resources_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resources_tags
    ADD CONSTRAINT resources_resources_tags_tag_id_58deb725_fk_resources_tag_id FOREIGN KEY (tag_id) REFERENCES public.resources_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resources resources_resources_uploaded_by_id_9abfb0e3_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resources
    ADD CONSTRAINT resources_resources_uploaded_by_id_9abfb0e3_fk_accounts_user_id FOREIGN KEY (uploaded_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resourcesubmission resources_resourcesu_approved_by_id_e344bae2_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resourcesubmission
    ADD CONSTRAINT resources_resourcesu_approved_by_id_e344bae2_fk_accounts_ FOREIGN KEY (approved_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resourcesubmission resources_resourcesu_category_id_3332309f_fk_resources; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resourcesubmission
    ADD CONSTRAINT resources_resourcesu_category_id_3332309f_fk_resources FOREIGN KEY (category_id) REFERENCES public.resources_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resourcesubmission resources_resourcesu_submitted_by_id_d102baf5_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: backup_srh_db_user
--

ALTER TABLE ONLY public.resources_resourcesubmission
    ADD CONSTRAINT resources_resourcesu_submitted_by_id_d102baf5_fk_accounts_ FOREIGN KEY (submitted_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO backup_srh_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO backup_srh_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO backup_srh_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO backup_srh_db_user;


--
-- PostgreSQL database dump complete
--

\unrestrict 0zjr6QXBrRiwQRNJIOqm9aI53eU1k66K4Pcj3HeJVsoZVXIjndfalEpXVBdUSpj

