# Generated by Django 5.2.14 on 2026-09-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='depertment',
            new_name='department',
        ),
    ]
