# Generated by Django 5.2.14 on 2026-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_depertment_user_department_remove_user_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='depertment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
