# Generated by Django 5.2.14 on 2026-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_department_user_depertment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='depertment',
            new_name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
