# Generated by Django 5.2.14 on 2026-05-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
