# Generated by Django 5.2.14 on 2026-05-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_rename_craeted_at_resources_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resources',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.tag'),
        ),
    ]
