# Generated by Django 5.2.14 on 2026-05-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_tag_resources_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='tags',
        ),
        migrations.AddField(
            model_name='resources',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
