# Generated by Django 5.2.14 on 2026-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_resources_tags_resources_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.tag'),
        ),
    ]
