# Generated by Django 5.2.14 on 2026-05-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resources_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('link', 'Link')], default='pdf', max_length=10),
        ),
    ]
