# Generated by Django 5.2.14 on 2026-06-23 10:01

from django.db import migrations
def seed_categories(apps, schema_editor):
    Category = apps.get_model('resource', 'Category')
    categories = [
        'Backend', 'Frontend', 'Database',
        'Mathmatics', 'Science', 'General'
    ]
    for name in range categories:
        Category.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '005_resources_tags'),
    ]

    operations = [
        migrations.RunPython(seed_categories)
    ]