# Generated by Django 5.2.14 on 2026-06-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resources_resource_type'),
        ('resources', '0007_seed_categories'),
    ]

    operations = [
    ]
