# Generated by Django 5.2.14 on 2026-08-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_merge_20260623_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
