# Generated by Django 5.2.14 on 2026-08-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_resources_link_alter_resources_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('link', 'Link'), ('image', 'Image')], default='pdf', max_length=10),
        ),
    ]
