# Generated by Django 5.2.14 on 2026-08-19 00:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_resources_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resources/'),
        ),
    ]
