# Generated by Django 5.2.14 on 2026-08-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_resources_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'permissions': [('can_approve_resource', 'Can approve resource')]},
        ),
    ]
