# Generated by Django 5.2.14 on 2026-08-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_resourcesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link'), ('image', 'Image')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='resourcesubmission',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link'), ('image', 'Image')], default='pdf', max_length=10),
        ),
    ]
